const BUILD=AEGIS.Core.BUILD;
const WEBHOOK='https://script.google.com/macros/s/AKfycbw4Rj-zD7L9TCi3ldYobavsKDiyUJ3hLJWhOUuu5PVc83NnzKc7xTdVzNykSgt3h5zSfA/exec';
const FALLBACK_LOCATION={lat:35.9954,lon:-78.8965,label:'Durham, NC',source:'Fallback'};
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c])),strip=s=>String(s||'').replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim();
let prefix='/note ',data={},doc={preamble:[],sections:[],byKey:{}},weatherLoc=loadWeatherLocation(),intel={categories:{},items:[],updated:null,source_health:[]},finance={transactions:[],summary:{}},notifications=[],capabilities=null,resolvedEvent=null;
function toast(msg,type='info'){const t=$('toast');if(!t)return;t.textContent=msg;t.dataset.type=type;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),3000)}
function busy(id,on,label){const b=$(id);if(!b)return;if(on){b.dataset.old=b.innerHTML;b.disabled=true;b.innerHTML=label}else{b.disabled=false;b.innerHTML=b.dataset.old||b.innerHTML}}
function stat(s,c='var(--ok)'){[$('status'),$('status2')].filter(Boolean).forEach(x=>{x.textContent=s;x.style.color=c})}
function setView(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===id));$('nav')?.classList.remove('open');$('scrim')?.classList.remove('show');window.scrollTo({top:0,behavior:'smooth'})}
function wireNavigation(){document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));document.querySelectorAll('[data-view-link]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.viewLink)));$('menuBtn')?.addEventListener('click',()=>{$('nav').classList.add('open');$('scrim').classList.add('show')});$('scrim')?.addEventListener('click',()=>{$('nav').classList.remove('open');$('scrim').classList.remove('show')});$('navCollapse')?.addEventListener('click',()=>{document.body.classList.toggle('nav-collapsed');$('nav').classList.toggle('collapsed')})}
function localNotification(title,message,severity='warning',type='client',detail=''){const key=[type,title,message].join('|');if(notifications.some(n=>!n.acknowledged&&n.key===key))return;notifications.unshift({id:'local-'+Date.now()+'-'+Math.random().toString(36).slice(2,6),key,title,message,severity,type,detail,createdAt:new Date().toISOString(),acknowledged:false,local:true});persistLocalNotifications();renderNotifications()}
function persistLocalNotifications(){try{localStorage.setItem('aegis_local_notifications',JSON.stringify(notifications.filter(n=>n.local).slice(0,50)))}catch{}}
function loadLocalNotifications(){try{return JSON.parse(localStorage.getItem('aegis_local_notifications')||'[]')}catch{return[]}}
function renderNotifications(){const active=notifications.filter(n=>!n.acknowledged);$('bellCount').textContent=active.length;$('bellCount').style.display=active.length?'grid':'none';const html=active.length?active.map(n=>`<div class="notification ${esc(n.severity)}"><strong>${esc(n.title)}</strong><div>${esc(n.message)}</div><div class="meta-line">${esc(n.type||'AEGIS')} • ${new Date(n.createdAt).toLocaleString()}</div>${n.detail?`<details><summary>Details</summary><div class="meta-line">${esc(n.detail)}</div></details>`:''}<div class="inline-actions left"><button class="mini" onclick="ackNotification('${esc(n.id)}')">Acknowledge</button></div></div>`).join(''):'<div class="muted">No unacknowledged notifications.</div>';$('notificationList').innerHTML=html;$('drawerNotifications').innerHTML=html;const critical=active.find(n=>n.severity==='critical');const pa=$('persistentAlert');if(critical){pa.innerHTML=`<strong>⚠ ${esc(critical.title)}</strong> — ${esc(critical.message)} <button class="mini" onclick="ackNotification('${esc(critical.id)}')">Acknowledge</button>`;pa.classList.remove('hidden')}else pa.classList.add('hidden')}
async function ackNotification(id){const n=notifications.find(x=>x.id===id);if(!n)return;n.acknowledged=true;if(n.local){persistLocalNotifications()}else{try{await post({action:'ack_notification',notificationId:id})}catch{}}renderNotifications()}
async function ackAll(){for(const n of notifications.filter(x=>!x.acknowledged)){n.acknowledged=true;if(!n.local){try{await post({action:'ack_notification',notificationId:n.id})}catch{}}}persistLocalNotifications();renderNotifications()}
async function syncNotifications(){try{const j=await AEGIS.Core.fetchJson(WEBHOOK+'?action=getNotifications&ts='+Date.now(),{cache:'no-store'},9000);if(Array.isArray(j.notifications)){const locals=notifications.filter(n=>n.local&&!n.acknowledged);notifications=[...j.notifications,...locals];renderNotifications();AEGIS.Core.setState('notifications','ready')}}catch(e){AEGIS.Core.setState('notifications','cached',e.message)}}
function rotateQuote(){const wrap=$('quoteWrap');if(!window.Q||!Q.length){$('qt').textContent='“Progress is built one reliable step at a time.”';$('qa').textContent='— AEGIS fallback';AEGIS.Core.setState('quotes','failed','Quote library unavailable; fallback active');return}const day=Math.floor(Date.now()/86400000),step=Number(sessionStorage.aegisQuoteStep||0),i=(day+step)%Q.length;const swap=()=>{$('qt').textContent='“'+Q[i][0]+'”';$('qa').textContent='— '+Q[i][1];sessionStorage.aegisQuoteStep=step+1;wrap.classList.remove('fading');AEGIS.Core.setState('quotes','ready',Q.length+' quotes loaded')};if(matchMedia('(prefers-reduced-motion: reduce)').matches)swap();else{wrap.classList.add('fading');setTimeout(swap,500)}}
async function post(payload,timeout=30000){const j=await AEGIS.Core.fetchJson(WEBHOOK,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(payload)},timeout);if(j.error||j.status==='error')throw Error(j.error||'AEGIS request failed');return j}
async function checkCapabilities(){try{capabilities=await AEGIS.Core.fetchJson(WEBHOOK+'?action=capabilities&ts='+Date.now(),{cache:'no-store'},8000);if(capabilities.backend_version!=='2.4.0')localNotification('AEGIS backend update required',`Frontend ${BUILD} is running but Apps Script reports ${capabilities.backend_version||'an older version'}. Some v2.4 features will use cached/degraded mode.`,'critical','backend-version');AEGIS.Core.setState('backend','ready','v'+(capabilities.backend_version||'?'))}catch(e){AEGIS.Core.setState('backend','failed',e.message);localNotification('AEGIS backend unavailable','Could not verify the Apps Script backend. Core cached data may still be shown.','critical','backend',e.message)}renderHealth()}
async function sendPayload(){const v=$('input').value.trim();if(!v)return;busy('send',1,'DISPATCHING…');stat('EXECUTING…','var(--warn)');try{const j=await post({message:prefix+v});$('out').textContent=j.result||j.message||JSON.stringify(j,null,2);$('input').value='';stat('SUCCESS');toast('Command dispatched');setTimeout(()=>loadDashboard(true),700)}catch(e){$('out').textContent='ERROR: '+e.message;stat('FAILED','var(--bad)');localNotification('Command dispatch failed',e.message,'critical','console')}finally{busy('send',0)}}
function openHorizonConfirm(){$('horizonConfirm').showModal()}
async function generateHorizon(){const dlg=$('horizonConfirm');if(dlg.open)dlg.close();busy('gen',1,'⚡ Generating…');stat('GENERATING…','var(--warn)');try{const j=await post({action:'horizon_sync',command:'/horizon'},90000);$('out').textContent=j.result||'HORIZON generated.';stat('HORIZON GENERATED');toast('New HORIZON generated');await loadDashboard(true);await syncNotifications()}catch(e){$('out').textContent='HORIZON ERROR: '+e.message;stat('GENERATION FAILED','var(--bad)');localNotification('HORIZON generation failed','The current valid briefing was preserved.','critical','horizon',e.message)}finally{busy('gen',0)}}
async function syncDashboard(){busy('sync',1,'↻ Syncing…');stat('SYNCING…','#8cddff');const jobs=[loadDashboard(true),syncWeather(false),syncIntelligence(false,false),syncFinance(false),syncNotifications()];const results=await Promise.allSettled(jobs);const failed=results.filter(x=>x.status==='rejected');if(failed.length){stat('PARTIAL','var(--warn)');toast(`Dashboard partial: ${failed.length} subsystem issue${failed.length===1?'':'s'}`);localNotification('Dashboard sync partial',`${failed.length} subsystem refresh${failed.length===1?'':'es'} failed. Open System Status for details.`,'warning','sync')}else{stat('SYSTEM READY');toast('Dashboard synced')}busy('sync',0);renderHealth()}
function stagedTaskIds(){try{return new Set(JSON.parse(localStorage.getItem('aegis_task_staged')||'[]'))}catch{return new Set()}}
function saveTaskIds(s){localStorage.setItem('aegis_task_staged',JSON.stringify([...s]))}
function stageTask(id,on){const s=stagedTaskIds();on?s.add(id):s.delete(id);saveTaskIds(s);renderTasks()}
async function syncTasks(){busy('tasksSync',1,'↻ Syncing…');try{const ids=[...stagedTaskIds()];if(ids.length){await post({action:'mark_done',completedTasks:ids,message:'mark_done:'});saveTaskIds(new Set())}await loadDashboard(true);toast(ids.length?`${ids.length} Google Task${ids.length===1?'':'s'} completed`:'Tasks refreshed');AEGIS.Core.setState('tasks','ready')}catch(e){AEGIS.Core.setState('tasks','failed',e.message);localNotification('Task sync failed',e.message,'critical','tasks');throw e}finally{busy('tasksSync',0)}}
async function syncSchedule(){busy('scheduleSync',1,'↻ Syncing…');try{await loadDashboard(true);AEGIS.Core.setState('calendar','ready');toast('Schedule synced')}catch(e){AEGIS.Core.setState('calendar','failed',e.message);localNotification('Schedule sync failed',e.message,'warning','calendar');throw e}finally{busy('scheduleSync',0)}}
function normalizeTitle(s){return String(s||'').replace(/\*\*/g,'').replace(/^\d+[.)]?\s*/,'').replace(/^[^\p{L}\p{N}]+/u,'').trim()}
function keyFor(s){const x=normalizeTitle(s).toLowerCase();if(x.includes('header')||x.includes('somatic'))return'somatic';if(x.includes('weather'))return'weather';if(x.includes('health')||x.includes('kinetic'))return'health';if(x.includes('sentinel')||x.includes('financial'))return'finance';if(x.startsWith('calendar'))return'calendar';if(x.includes('active tasks')||x==='tasks')return'tasks';if(x.includes('gmail')||x.includes('logistics tracking'))return'gmail';if(x.includes('things to consider')||x.includes('strategic notes'))return'ideas';if(x.includes('personal newspaper')||x==='newspaper')return'news';return x.replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
function parseHorizon(text){const out={preamble:[],sections:[],byKey:{}};let current=null,sub=null;String(text||'').replace(/\r\n?/g,'\n').split('\n').forEach(line=>{const t=line.trim();if(t==='---')return;const h=t.match(/^(#{2,4})\s+(.*)$/);if(h){const level=h[1].length,title=normalizeTitle(h[2]);if(level===2){current={title,key:keyFor(title),lines:[],subsections:[]};out.sections.push(current);out.byKey[current.key]=current;sub=null}else if(current){sub={title,lines:[]};current.subsections.push(sub)}return}if(!current){if(!/^#\s+/.test(t))out.preamble.push(line);return}(sub?sub.lines:current.lines).push(line)});return out}
function inline(s){let x=esc(s);x=x.replace(/\[([^\]]+)\]\((https?:\/\/[^)]+)\)/g,'<a href="$2" target="_blank" rel="noopener noreferrer">$1 ↗</a>');return x.replace(/\*\*(.*?)\*\*/g,'<strong>$1</strong>').replace(/(?<!\*)\*([^*]+)\*/g,'<em>$1</em>').replace(/`([^`]+)`/g,'<code>$1</code>')}
function renderMd(lines){if(!lines?.length)return '<span class="muted">No current HORIZON content.</span>';let o='';for(const raw of lines){const x=raw.trim();if(!x)continue;const nested=/^\s{2,}[-*]\s+(.*)$/.exec(raw),task=/^[-*]\s+\[[ xX]\]\s+(.*)$/.exec(x),bullet=/^[-*]\s+(.*)$/.exec(x),num=/^\d+[.)]\s+(.*)$/.exec(x);if(nested)o+='<div class="subbullet">'+inline(nested[1])+'</div>';else if(task||bullet||num)o+='<div class="bullet">'+inline((task||bullet||num)[1])+'</div>';else if(/^>\s*/.test(x))o+='<p><em>'+inline(x.replace(/^>\s*/,''))+'</em></p>';else o+='<p>'+inline(x)+'</p>'}return o}
function renderSection(id,key){const s=doc.byKey[key];let html=s?renderMd(s.lines):'<span class="muted">No current HORIZON content.</span>';if(s?.subsections?.length)html+=s.subsections.map(z=>'<h4>'+inline(z.title)+'</h4>'+renderMd(z.lines)).join('');$(id).innerHTML=html}
function localStore(k){try{return new Set(JSON.parse(localStorage.getItem('aegis_'+k)||'[]'))}catch{return new Set()}}
function toggleLocal(k,t,on){const s=localStore(k),n=t.toLowerCase().trim();on?s.add(n):s.delete(n);localStorage.setItem('aegis_'+k,JSON.stringify([...s]));k==='horizonTasks'?renderHorizonTasks():renderIdeas()}
function renderTasks(){const ts=data.tasks||[],st=stagedTaskIds();$('taskN').textContent=ts.length;$('taskStaged').textContent=st.size?`${st.size} task${st.size===1?'':'s'} staged for completion on Sync Tasks.`:'No staged completions.';const row=t=>{const d=st.has(t.id);return `<div class="item ${d?'done':''}"><input class="check" type="checkbox" ${d?'checked':''} onchange='stageTask(${JSON.stringify(t.id)},this.checked)'><span><div class="item-title">${esc(t.title||'Untitled Task')}</div><div class="item-sub">${d?'Staged for completion':esc(t.time||'Google Task')} • <a href="https://tasks.google.com/" target="_blank" rel="noopener">Open Tasks ↗</a></div></span></div>`};$('tasks').innerHTML=ts.length?ts.map(row).join(''):'<span class="muted">No active Google Tasks returned.</span>';$('overviewTasks').innerHTML=ts.length?ts.slice(0,4).map(row).join(''):'<span class="muted">No active tasks.</span>'}
function taskSourceLines(){const s=doc.byKey.tasks;if(!s)return[];const priority=s.subsections.find(z=>/action priorit/i.test(z.title));return (priority?priority.lines:s.lines).map(x=>x.trim()).filter(x=>/^([-*]|\d+[.)])\s+/.test(x)).map(x=>x.replace(/^[-*]\s+\[[ xX]\]\s*/,'').replace(/^[-*]\s+/,'').replace(/^\d+[.)]\s+/,'').trim())}
function renderHorizonTasks(){const a=taskSourceLines(),s=localStore('horizonTasks'),show=$('showHorizonTasks').checked;$('horizonTasks').innerHTML=a.length?a.map(t=>{const plain=strip(t.replace(/\*\*/g,'')),d=s.has(plain.toLowerCase());return `<label class="item ${d?'done':''}" style="${d&&!show?'display:none':''}"><input class="check" type="checkbox" ${d?'checked':''} onchange='toggleLocal("horizonTasks",${JSON.stringify(plain)},this.checked)'><span class="item-title">${inline(t)}</span></label>`}).join(''):'<span class="muted">No HORIZON-generated actions.</span>'}
function ideaLines(){const s=doc.byKey.ideas;if(!s)return[];return s.lines.map(x=>x.trim()).filter(x=>/^[-*]\s+/.test(x)).map(x=>x.replace(/^[-*]\s+/,'').trim())}
function renderIdeas(){const a=ideaLines(),s=localStore('ideas'),show=$('showIdeas').checked;$('ideas').innerHTML=a.length?a.map(t=>{const plain=strip(t.replace(/\*\*/g,'')),d=s.has(plain.toLowerCase());return `<label class="item ${d?'done':''}" style="${d&&!show?'display:none':''}"><input class="check" type="checkbox" ${d?'checked':''} onchange='toggleLocal("ideas",${JSON.stringify(plain)},this.checked)'><span class="item-title">${inline(t)}</span></label>`}).join(''):'<span class="muted">No current Things to Consider.</span>'}
function eventHtml(a){return a?.length?a.map(e=>`<div class="event" onclick="window.open('https://calendar.google.com/calendar/u/0/r','_blank')"><small>${esc(e.time||'All day')}</small><div class="item-title">${esc(e.title)}</div>${e.note?`<div class="note">${esc(e.note)}</div>`:''}<div class="item-sub">Open Calendar ↗</div></div>`).join(''):'<span class="muted">No scheduled events.</span>'}
function renderDashboard(){const today=data.calendar?.today||[],tom=data.calendar?.tomorrow||[];$('eventN').textContent=today.length;['timeline','todaySchedule'].forEach(id=>$(id).innerHTML=eventHtml(today));$('tomorrowSchedule').innerHTML=eventHtml(tom);renderTasks();renderHorizonTasks();renderIdeas();$('preamble').innerHTML=renderMd(doc.preamble);['somatic','weather','health','finance','gmail','news'].forEach(k=>renderSection(k,k));renderSection('calendarBrief','calendar');const u=data.briefing?.last_updated||data.system_metadata?.last_updated;$('updated').textContent=u?'Briefing updated '+new Date(u).toLocaleString():'Briefing loaded';const hs=data.system_metadata?.horizon_generation||{};$('horizonStatus').textContent=hs.last_success?`Last successful HORIZON: ${new Date(hs.last_success).toLocaleString()} • ${hs.mode||'manual'}`:'No automated HORIZON status returned yet.'}
function diag(raw){const expected=['somatic','weather','health','finance','calendar','tasks','gmail','ideas','news'],found=expected.filter(k=>doc.byKey[k]);$('diag').innerHTML=`Frontend build: <b>${BUILD}</b><br>Backend: ${esc(capabilities?.backend_version||'unknown')}<br>HORIZON characters: ${raw.length}<br>Detected top-level sections: ${doc.sections.length}<br>Mapped expected sections: ${found.length}/9<br>Quote count: ${window.Q?.length||0}<br>Weather location: ${esc(weatherLoc.label||'unknown')}<br>Intelligence items: ${intel.items?.length||0}<br>Finance rows (72h): ${finance.transactions?.length||0}`}
async function loadDashboard(force=false){const cached=AEGIS.Core.load('dashboard');if(cached&&!force){data=cached.data;const raw=data.briefing?.plain_text||'';doc=parseHorizon(raw);renderDashboard();$('rawBrief').textContent=raw||'No cached briefing.'}const j=await AEGIS.Core.fetchJson(WEBHOOK+'?action=getHorizonData&ts='+Date.now(),{cache:'no-store'},12000);if(j.status==='error')throw Error(j.error);data=j;AEGIS.Core.save('dashboard',j,{source:'apps-script'});const raw=j.briefing?.plain_text||'';doc=parseHorizon(raw);renderDashboard();diag(raw);$('rawBrief').textContent=raw||'No canonical briefing returned.';AEGIS.Core.setState('dashboard','ready');AEGIS.Core.setState('calendar','ready');AEGIS.Core.setState('tasks','ready');return j}
function clock(){const now=new Date();$('liveClock').textContent=now.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});$('liveDate').textContent=now.toLocaleDateString([],{weekday:'long',month:'short',day:'numeric'})}
function loadWeatherLocation(){try{return JSON.parse(localStorage.getItem('aegis_weather_location'))||FALLBACK_LOCATION}catch{return FALLBACK_LOCATION}}
function saveWeatherLocation(x){weatherLoc=x;localStorage.setItem('aegis_weather_location',JSON.stringify(x))}
function locate(){return new Promise(resolve=>{if(!navigator.geolocation)return resolve(FALLBACK_LOCATION);navigator.geolocation.getCurrentPosition(async p=>{let loc={lat:p.coords.latitude,lon:p.coords.longitude,label:`${p.coords.latitude.toFixed(3)}, ${p.coords.longitude.toFixed(3)}`,source:'Live location'};try{const j=await AEGIS.Core.fetchJson(WEBHOOK+`?action=reverseGeocode&lat=${loc.lat}&lon=${loc.lon}&ts=${Date.now()}`,{cache:'no-store'},7000);if(j.label)loc.label=j.label}catch{}saveWeatherLocation(loc);resolve(loc)},()=>resolve(weatherLoc||FALLBACK_LOCATION),{enableHighAccuracy:false,timeout:7000,maximumAge:900000})})}
function weatherCode(c){return({0:'Clear',1:'Mostly clear',2:'Partly cloudy',3:'Overcast',45:'Fog',48:'Rime fog',51:'Light drizzle',53:'Drizzle',55:'Heavy drizzle',61:'Light rain',63:'Rain',65:'Heavy rain',71:'Light snow',73:'Snow',75:'Heavy snow',80:'Rain showers',81:'Showers',82:'Heavy showers',95:'Thunderstorms',96:'Thunderstorms + hail',99:'Severe thunderstorms'})[c]||'Current conditions'}
async function syncWeather(forceLocation=false){busy('weatherSync',1,'↻ Syncing…');const cached=AEGIS.Core.load('weather');if(cached&&!forceLocation)renderWeather(cached.data,true);try{const loc=forceLocation?await locate():(weatherLoc||await locate());weatherLoc=loc;const url=`https://api.open-meteo.com/v1/forecast?latitude=${encodeURIComponent(loc.lat)}&longitude=${encodeURIComponent(loc.lon)}&current=temperature_2m,apparent_temperature,relative_humidity_2m,weather_code,wind_speed_10m&hourly=temperature_2m,precipitation_probability,weather_code&daily=temperature_2m_max,temperature_2m_min&temperature_unit=fahrenheit&wind_speed_unit=mph&timezone=auto&forecast_days=2`;const w=await AEGIS.Core.fetchJson(url,{cache:'no-store'},10000);const payload={w,loc,updated:new Date().toISOString()};AEGIS.Core.save('weather',payload,{source:'open-meteo'});renderWeather(payload,false);AEGIS.Core.setState('weather','ready')}catch(e){AEGIS.Core.setState('weather',cached?'cached':'failed',e.message);if(!cached)localNotification('Weather unavailable',e.message,'warning','weather');throw e}finally{busy('weatherSync',0);renderHealth()}}
function renderWeather(payload,cached){if(!payload)return;const {w,loc}=payload,cur=w.current||{},d=w.daily||{};$('weatherLocation').textContent=`${loc.label} • ${cached?'Cached':loc.source}`;$('weatherTemp').textContent=Math.round(cur.temperature_2m)+'°F';$('weatherCondition').textContent=weatherCode(cur.weather_code);$('weatherFeels').textContent=Math.round(cur.apparent_temperature)+'°F';$('weatherHiLo').textContent=`${Math.round(d.temperature_2m_max?.[0])}° / ${Math.round(d.temperature_2m_min?.[0])}°`;$('weatherHumidity').textContent=Math.round(cur.relative_humidity_2m)+'%';const times=w.hourly?.time||[],rows=[];for(let i=0;i<times.length&&rows.length<6;i++)if(new Date(times[i]).getTime()>=Date.now()-1800000)rows.push({time:times[i],temp:w.hourly.temperature_2m[i],rain:w.hourly.precipitation_probability[i]});$('weatherRain').textContent=(rows[0]?.rain??0)+'%';$('weatherWind').textContent=Math.round(cur.wind_speed_10m)+' mph';$('weatherUpdated').textContent=new Date(payload.updated).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});$('weatherHourly').innerHTML=rows.map(x=>`<div class="hour"><small>${new Date(x.time).toLocaleTimeString([],{hour:'numeric'})}</small><b>${Math.round(x.temp)}°</b><small>${x.rain??0}% rain</small></div>`).join('')}
function intelLabel(k){return({'local-triangle':'Durham / Triangle','nc-policy':'NC / Policy & Health','pc-gaming':'PC Gaming','game-updates':'Game Updates','tarkov':'Escape from Tarkov','industry':'Gaming Industry','deals':'Game Deals','ai-cyber':'AI / Cybersecurity'})[k]||k}
function renderIntelItem(x){return `<article class="intel-item"><div class="intel-title"><a href="${esc(x.link||'#')}" target="_blank" rel="noopener noreferrer">${esc(x.title||'Untitled')} ↗</a></div><div class="intel-meta">${esc(x.source||'Source')} • ${x.published?esc(new Date(x.published).toLocaleString()):'Recent'} <span class="source-badge">${esc(x.sourceType||'Editorial')}</span></div>${x.description?`<div class="intel-desc">${esc(strip(x.description).slice(0,260))}</div>`:''}</article>`}
function renderIntel(cached=false){const entries=Object.entries(intel.categories||{});$('intelN').textContent=intel.items?.length||0;$('intelSections').innerHTML=entries.length?entries.map(([k,a],idx)=>`<details class="intel-category" ${idx<2?'open':''}><summary><span>${esc(intelLabel(k))}</span><span class="source-badge">${a.length} items</span></summary><div class="intel-list">${a.map(renderIntelItem).join('')}</div></details>`).join(''):'<div class="muted">No Intelligence data available.</div>';$('intelPreview').innerHTML=(intel.items||[]).slice(0,6).map(renderIntelItem).join('')||'<span class="muted">No live intelligence loaded.</span>';const errs=intel.source_errors||[],status=intel.status||'ready';$('intelState').innerHTML=`<strong>${cached?'CACHED':status.toUpperCase()}</strong> • ${(intel.items||[]).length} items • ${errs.length?errs.length+' source issue(s)':'all available sources healthy'} • Updated ${intel.updated?new Date(intel.updated).toLocaleString():'unknown'}`;const health=intel.source_health||[];$('intelSourceHealth').innerHTML=health.length?health.map(h=>`<div class="health-card"><strong>${esc(h.source)}</strong><span class="status-${h.status==='ready'?'ready':'failed'}">${esc(String(h.status||'unknown').toUpperCase())}</span><small>${h.items||0} items${h.http?' • HTTP '+h.http:''}${h.error?' • '+esc(h.error):''}</small></div>`).join(''):'<span class="muted">Source health will populate after the v2.4 backend refreshes Intelligence.</span>'}
async function syncIntelligence(showToast=true,force=true){busy('intelSync',1,'↻ Syncing…');const cached=AEGIS.Core.load('intelligence');if(cached){intel=cached.data;renderIntel(true)}try{const j=await AEGIS.Core.fetchJson(WEBHOOK+`?action=getIntelligence&force=${force?1:0}&ts=${Date.now()}`,{cache:'no-store'},22000);if(!j.categories)throw Error(j.error||'Intelligence endpoint unavailable');intel=j;AEGIS.Core.save('intelligence',j,{source:'apps-script'});renderIntel(false);const status=(j.source_errors||[]).length?'partial':'ready';AEGIS.Core.setState('intelligence',status,(j.source_errors||[]).length?`${j.source_errors.length} feed failures`:'');if(showToast)toast(status==='partial'?'Intelligence synced with feed warnings':'Live Intelligence synced');if(status==='partial')localNotification('Intelligence partially refreshed',`${j.source_errors.length} feed source(s) failed; successful feeds are still available.`,'warning','intelligence')}catch(e){AEGIS.Core.setState('intelligence',cached?'cached':'failed',e.message);if(!cached)localNotification('Live Intelligence unavailable','No cached Intelligence was available.','critical','intelligence',e.message);if(showToast)toast(cached?'Using cached Intelligence':'Intelligence failed');if(!cached)throw e}finally{busy('intelSync',0);renderHealth()}}
function renderTransaction(t){const credit=Number(t.amount)<0;return `<div class="transaction"><div class="transaction-head"><strong>${esc(t.vendor)}</strong><span class="transaction-amount ${credit?'credit':''}">${credit?'-':' '}$${Math.abs(Number(t.amount||0)).toFixed(2)}</span></div><div class="transaction-meta">${esc(t.category||'Uncategorized')} • ${esc(t.paymentSource||'Unknown source')} • ${new Date(t.occurredAt).toLocaleString()}</div>${t.notes?`<details><summary>Details</summary><div class="transaction-meta">${esc(t.notes)}</div></details>`:''}</div>`}
function renderFinance(){const s=finance.summary||{};$('spend72').textContent=s.purchaseTotal===undefined?'—':'$'+Number(s.purchaseTotal).toFixed(2);$('financePurchases').textContent=s.purchaseTotal===undefined?'—':'$'+Number(s.purchaseTotal).toFixed(2);$('financeCredits').textContent=s.creditTotal===undefined?'—':'-$'+Math.abs(Number(s.creditTotal)).toFixed(2);$('financeCount').textContent=finance.transactions?.length||0;$('financeUpdated').textContent=finance.updated?new Date(finance.updated).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):'—';$('financeActivity').innerHTML=(finance.transactions||[]).map(renderTransaction).join('')||'<span class="muted">No qualifying activity in the last 72 hours.</span>';$('financePreview').innerHTML=(finance.transactions||[]).slice(0,6).map(renderTransaction).join('')||'<span class="muted">No recent activity.</span>'}
async function syncFinance(showToast=true){busy('financeSync',1,'↻ Syncing…');const cached=AEGIS.Core.load('finance');if(cached){finance=cached.data;renderFinance()}try{const j=await AEGIS.Core.fetchJson(WEBHOOK+'?action=getRecentFinance&hours=72&ts='+Date.now(),{cache:'no-store'},12000);if(!Array.isArray(j.transactions))throw Error(j.error||'Finance endpoint unavailable');finance=j;AEGIS.Core.save('finance',j,{source:'apps-script'});renderFinance();AEGIS.Core.setState('finance','ready');if(showToast)toast('Finance synced')}catch(e){AEGIS.Core.setState('finance',cached?'cached':'failed',e.message);if(!cached)localNotification('Finance sync unavailable','Recent activity endpoint is unavailable until the v2.4 Apps Script is deployed.','warning','finance',e.message);if(!cached&&showToast)toast('Finance sync failed');if(!cached)throw e}finally{busy('financeSync',0);renderHealth()}}
async function resolveCalendarEvent(){const text=$('eventInput').value.trim();if(!text)return;busy('resolveEvent',1,'Resolving…');try{const j=await post({action:'resolve_calendar_event',text},30000);resolvedEvent=j.event;if(!resolvedEvent)throw Error(j.error||'No event resolved');$('eventPreview').innerHTML=`<strong>${esc(resolvedEvent.title)}</strong><br>${new Date(resolvedEvent.start).toLocaleString()} → ${new Date(resolvedEvent.end).toLocaleString()}${resolvedEvent.location?`<br>${esc(resolvedEvent.location)}`:''}${resolvedEvent.description?`<br><span class="muted">${esc(resolvedEvent.description)}</span>`:''}<div class="inline-actions left mt"><button class="mini primary" id="confirmEventCreate">Add to Calendar</button><button class="mini" id="cancelEventCreate">Cancel</button></div>`;$('confirmEventCreate').onclick=createCalendarEvent;$('cancelEventCreate').onclick=()=>{resolvedEvent=null;$('eventPreview').textContent='Cancelled. Nothing was written to Calendar.'}}catch(e){localNotification('Calendar event could not be resolved',e.message,'warning','calendar-create');$('eventPreview').textContent='Resolve failed: '+e.message}finally{busy('resolveEvent',0)}}
async function createCalendarEvent(){if(!resolvedEvent)return;try{const j=await post({action:'create_calendar_event',event:resolvedEvent});toast('Event added to Google Calendar');$('eventPreview').innerHTML=`<strong>Added:</strong> ${esc(j.event?.title||resolvedEvent.title)} <a href="https://calendar.google.com/calendar/u/0/r" target="_blank">Open Calendar ↗</a>`;resolvedEvent=null;await loadDashboard(true)}catch(e){localNotification('Calendar event creation failed',e.message,'critical','calendar-create')}}
function renderHealth(){const states=AEGIS.Core.getStates();const names=['backend','dashboard','calendar','tasks','finance','weather','intelligence','notifications','quotes'];$('healthGrid').innerHTML=names.map(n=>{const s=states[n]||{status:'unknown',detail:''};return `<div class="health-card"><strong>${esc(n.toUpperCase())}</strong><span class="status-${esc(s.status)}">${esc(s.status.toUpperCase())}</span><small>${esc(s.detail||s.updatedAt||'Not checked')}</small></div>`}).join('');const severe=Object.values(states).some(s=>s.status==='failed'),degraded=Object.values(states).some(s=>['partial','cached'].includes(s.status));const btn=$('systemState');btn.textContent=severe?'● DEGRADED':degraded?'● PARTIAL':'● ONLINE';btn.style.color=severe?'var(--bad)':degraded?'var(--warn)':'var(--ok)'}
async function installAutomation(){busy('automationInstall',1,'Installing…');try{await post({action:'install_automation_triggers'});toast('AEGIS automation triggers installed');localNotification('AEGIS automation enabled','Morning HORIZON, hourly Intelligence refresh, and appointment reminder sweeps are installed.','warning','automation');await checkCapabilities()}catch(e){localNotification('Automation trigger installation failed',e.message,'critical','automation');throw e}finally{busy('automationInstall',0)}}
async function healthCheck(){busy('healthSync',1,'Checking…');await Promise.allSettled([checkCapabilities(),syncNotifications()]);renderHealth();busy('healthSync',0)}
function wire(){wireNavigation();document.querySelectorAll('.chip').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.chip').forEach(x=>x.classList.remove('on'));b.classList.add('on');prefix=b.dataset.p;$('target').textContent='TARGET: '+prefix.trim();$('input').focus()}));$('input').addEventListener('keydown',e=>{if((e.ctrlKey||e.shiftKey)&&e.key==='Enter'){e.preventDefault();sendPayload()}});$('send').onclick=sendPayload;$('gen').onclick=openHorizonConfirm;$('confirmHorizon').onclick=generateHorizon;$('cancelHorizon').onclick=()=>$('horizonConfirm').close();$('sync').onclick=syncDashboard;$('tasksSync').onclick=syncTasks;$('scheduleSync').onclick=syncSchedule;$('weatherSync').onclick=()=>syncWeather(true);$('intelSync').onclick=()=>syncIntelligence(true,true);$('financeSync').onclick=()=>syncFinance(true);$('resolveEvent').onclick=resolveCalendarEvent;$('intelExpand').onclick=()=>document.querySelectorAll('.intel-category').forEach(x=>x.open=true);$('intelCollapse').onclick=()=>document.querySelectorAll('.intel-category').forEach(x=>x.open=false);$('showHorizonTasks').onchange=renderHorizonTasks;$('showIdeas').onchange=renderIdeas;$('bellBtn').onclick=()=>$('notificationDrawer').classList.add('open');$('closeNotifications').onclick=()=>$('notificationDrawer').classList.remove('open');$('ackAll').onclick=ackAll;$('healthSync').onclick=healthCheck;$('automationInstall').onclick=installAutomation}
(async function init(){wire();notifications=loadLocalNotifications();renderNotifications();rotateQuote();setInterval(rotateQuote,30000);clock();setInterval(clock,1000);const cachedDash=AEGIS.Core.load('dashboard');if(cachedDash){data=cachedDash.data;doc=parseHorizon(data.briefing?.plain_text||'');renderDashboard()}const cachedIntel=AEGIS.Core.load('intelligence');if(cachedIntel){intel=cachedIntel.data;renderIntel(true)}const cachedFinance=AEGIS.Core.load('finance');if(cachedFinance){finance=cachedFinance.data;renderFinance()}const cachedWeather=AEGIS.Core.load('weather');if(cachedWeather)renderWeather(cachedWeather.data,true);await Promise.allSettled([checkCapabilities(),loadDashboard(true),syncWeather(false),syncIntelligence(false,false),syncFinance(false),syncNotifications()]);renderHealth();setInterval(syncNotifications,5*60*1000);setInterval(()=>syncWeather(false),20*60*1000);if('serviceWorker'in navigator)addEventListener('load',async()=>{try{const r=await navigator.serviceWorker.register('./sw.js?v='+BUILD);await r.update()}catch{}})})();
