const BUILD='2.3.0';
const WEBHOOK='https://script.google.com/macros/s/AKfycbw4Rj-zD7L9TCi3ldYobavsKDiyUJ3hLJWhOUuu5PVc83NnzKc7xTdVzNykSgt3h5zSfA/exec';
const FALLBACK_LOCATION={lat:35.9954,lon:-78.8965,label:'Durham, NC',source:'Fallback'};
let prefix='/note ',data={},doc={preamble:[],sections:[],byKey:{}},weatherLoc=loadWeatherLocation(),intel={categories:{},items:[],updated:null};
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const strip=s=>String(s||'').replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim();
function toast(s){$('toast').textContent=s;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2800)}
function busy(id,on,label){const b=$(id);if(!b)return;if(on){b.dataset.old=b.innerHTML;b.disabled=true;b.innerHTML=label}else{b.disabled=false;b.innerHTML=b.dataset.old||b.innerHTML}}
function stat(s,c='var(--ok)'){if($('status')){$('status').textContent=s;$('status').style.color=c}if($('status2')){$('status2').textContent=s;$('status2').style.color=c}}
function rotateQuote(){if(!window.Q||!Q.length)return;const wrap=$('quoteWrap');const day=Math.floor(Date.now()/86400000),step=Number(sessionStorage.aegisQuoteStep||0),i=(day+step)%Q.length;const swap=()=>{$('qt').textContent='“'+Q[i][0]+'”';$('qa').textContent='— '+Q[i][1];sessionStorage.aegisQuoteStep=step+1;wrap.classList.remove('fading')};if(window.matchMedia('(prefers-reduced-motion: reduce)').matches)swap();else{wrap.classList.add('fading');setTimeout(swap,520)}}
setTimeout(rotateQuote,40);setInterval(rotateQuote,30000);
function setView(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===id));document.querySelector('.nav')?.classList.remove('open');$('scrim')?.classList.remove('show');window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));
document.querySelectorAll('[data-view-link]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.viewLink)));
$('menuBtn')?.addEventListener('click',()=>{$('nav').classList.add('open');$('scrim').classList.add('show')});$('scrim')?.addEventListener('click',()=>{$('nav').classList.remove('open');$('scrim').classList.remove('show')});$('navCollapse')?.addEventListener('click',()=>{document.body.classList.toggle('nav-collapsed');$('nav').classList.toggle('collapsed')});
document.querySelectorAll('.chip').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.chip').forEach(x=>x.classList.remove('on'));b.classList.add('on');prefix=b.dataset.p;$('target').textContent='TARGET: '+prefix.trim();$('input').focus()}));
$('input').addEventListener('keydown',e=>{if((e.ctrlKey||e.shiftKey)&&e.key==='Enter'){e.preventDefault();sendPayload()}});$('send').addEventListener('click',sendPayload);$('gen').addEventListener('click',generateHorizon);$('sync').addEventListener('click',syncDashboard);$('tasksSync').addEventListener('click',syncTasks);$('scheduleSync').addEventListener('click',syncSchedule);$('weatherSync').addEventListener('click',()=>syncWeather(true));$('intelSync').addEventListener('click',syncIntelligence);$('intelExpand').addEventListener('click',()=>document.querySelectorAll('.intel-category').forEach(x=>x.open=true));$('intelCollapse').addEventListener('click',()=>document.querySelectorAll('.intel-category').forEach(x=>x.open=false));$('showHorizonTasks').addEventListener('change',renderHorizonTasks);$('showIdeas').addEventListener('change',renderIdeas);
async function post(payload){const r=await fetch(WEBHOOK,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(payload)});const j=await r.json();if(j.status==='error'||j.error)throw Error(j.error||'AEGIS request failed');return j}
async function sendPayload(){const v=$('input').value.trim();if(!v)return;busy('send',1,'DISPATCHING…');stat('EXECUTING…','var(--warn)');try{const j=await post({message:prefix+v});$('out').textContent=j.result||j.message||JSON.stringify(j,null,2);if(j.totalCalories!==undefined)$('cal').textContent=j.totalCalories+' kcal';$('input').value='';stat('SUCCESS');toast('Command dispatched');setTimeout(loadDashboard,700)}catch(e){$('out').textContent='ERROR: '+e.message;stat('FAILED','var(--bad)')}finally{busy('send',0)}}
async function generateHorizon(){busy('gen',1,'⚡ GENERATING HORIZON…');stat('GENERATING…','var(--warn)');try{const j=await post({action:'horizon_sync',command:'/horizon'});$('out').textContent=j.result||j.message||'HORIZON generated.';stat('HORIZON GENERATED');toast('New HORIZON generated');await loadDashboard()}catch(e){$('out').textContent='HORIZON ERROR: '+e.message;stat('GENERATION FAILED','var(--bad)')}finally{busy('gen',0)}}
async function syncDashboard(){busy('sync',1,'↻ SYNCING…');stat('SYNCING…','#8cddff');try{await Promise.allSettled([loadDashboard(),syncWeather(false),syncIntelligence(false)]);stat('SYSTEM READY');toast('Dashboard synced')}catch(e){$('out').textContent='SYNC ERROR: '+e.message;stat('SYNC FAILED','var(--bad)')}finally{busy('sync',0)}}
async function syncSchedule(){busy('scheduleSync',1,'↻ Syncing…');try{await loadDashboard();toast('Schedule synced')}finally{busy('scheduleSync',0)}}
function stagedTaskIds(){try{return new Set(JSON.parse(localStorage.getItem('aegis_task_staged')||'[]'))}catch{return new Set()}}
function saveTaskIds(s){localStorage.setItem('aegis_task_staged',JSON.stringify([...s]))}
function stageTask(id,on){const s=stagedTaskIds();on?s.add(id):s.delete(id);saveTaskIds(s);renderTasks()}
async function syncTasks(){busy('tasksSync',1,'↻ Syncing…');try{const ids=[...stagedTaskIds()];if(ids.length){await post({action:'mark_done',completedTasks:ids,message:'mark_done:'});saveTaskIds(new Set())}await loadDashboard();toast(ids.length?`${ids.length} Google Task${ids.length===1?'':'s'} completed`:'Tasks refreshed')}catch(e){$('out').textContent='TASK SYNC ERROR: '+e.message;toast('Task sync failed')}finally{busy('tasksSync',0)}}
function normalizeTitle(s){return String(s||'').replace(/\*\*/g,'').replace(/^\d+[.)]?\s*/,'').replace(/^[^\p{L}\p{N}]+/u,'').trim()}
function keyFor(s){const x=normalizeTitle(s).toLowerCase();if(x.includes('header')||x.includes('somatic'))return'somatic';if(x.includes('weather'))return'weather';if(x.includes('health')||x.includes('kinetic'))return'health';if(x.includes('sentinel')||x.includes('financial'))return'finance';if(x.startsWith('calendar'))return'calendar';if(x.includes('active tasks')||x==='tasks')return'tasks';if(x.includes('gmail')||x.includes('logistics tracking'))return'gmail';if(x.includes('things to consider')||x.includes('strategic notes'))return'ideas';if(x.includes('personal newspaper')||x==='newspaper')return'news';return x.replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
function parseHorizon(text){const out={preamble:[],sections:[],byKey:{}};let current=null,sub=null;String(text||'').replace(/\r\n?/g,'\n').split('\n').forEach(line=>{const t=line.trim();if(t==='---')return;const h=t.match(/^(#{2,4})\s+(.*)$/);if(h){const level=h[1].length,title=normalizeTitle(h[2]);if(level===2){current={title,key:keyFor(title),lines:[],subsections:[]};out.sections.push(current);out.byKey[current.key]=current;sub=null}else if(current){sub={title,lines:[]};current.subsections.push(sub)}return}if(!current){if(!/^#\s+/.test(t))out.preamble.push(line);return}(sub?sub.lines:current.lines).push(line)});return out}
function inline(s){let x=esc(s);x=x.replace(/\[([^\]]+)\]\((https?:\/\/[^)]+)\)/g,'<a href="$2" target="_blank" rel="noopener noreferrer">$1 ↗</a>');return x.replace(/\*\*(.*?)\*\*/g,'<strong>$1</strong>').replace(/(?<!\*)\*([^*]+)\*/g,'<em>$1</em>').replace(/`([^`]+)`/g,'<code>$1</code>')}
function renderMd(lines){if(!lines?.length)return '<span class="muted">No current HORIZON content.</span>';let o='';for(const raw of lines){const x=raw.trim();if(!x)continue;const nested=/^\s{2,}[-*]\s+(.*)$/.exec(raw),task=/^[-*]\s+\[[ xX]\]\s+(.*)$/.exec(x),bullet=/^[-*]\s+(.*)$/.exec(x),num=/^\d+[.)]\s+(.*)$/.exec(x);if(nested)o+='<div class="subbullet">'+inline(nested[1])+'</div>';else if(task)o+='<div class="bullet">'+inline(task[1])+'</div>';else if(bullet)o+='<div class="bullet">'+inline(bullet[1])+'</div>';else if(num)o+='<div class="bullet">'+inline(num[1])+'</div>';else if(/^>\s*/.test(x))o+='<p><em>'+inline(x.replace(/^>\s*/,''))+'</em></p>';else o+='<p>'+inline(x)+'</p>'}return o}
function renderSection(id,key,filterSub){const s=doc.byKey[key];let html=s?renderMd(s.lines):'<span class="muted">No current HORIZON content.</span>';if(s?.subsections?.length)html+=s.subsections.filter(z=>!filterSub||filterSub(z)).map(z=>'<h4>'+inline(z.title)+'</h4>'+renderMd(z.lines)).join('');$(id).innerHTML=html}
function localStore(k){try{return new Set(JSON.parse(localStorage.getItem('aegis_'+k)||'[]'))}catch{return new Set()}}
function toggleLocal(k,t,on){const s=localStore(k),n=t.toLowerCase().trim();on?s.add(n):s.delete(n);localStorage.setItem('aegis_'+k,JSON.stringify([...s]));k==='horizonTasks'?renderHorizonTasks():renderIdeas()}
function renderTasks(){const ts=data.tasks||[],st=stagedTaskIds();$('taskN').textContent=ts.length;$('taskStaged').textContent=st.size?`${st.size} task${st.size===1?'':'s'} staged for completion on Sync Tasks.`:'No staged completions.';const html=ts.length?ts.map(t=>{const d=st.has(t.id),label=t.title||'Untitled Task';return `<label class="item ${d?'done':''}"><input class="check" type="checkbox" ${d?'checked':''} onchange='stageTask(${JSON.stringify(t.id)},this.checked)'><span><div class="item-title">${esc(label)}</div><div class="item-sub">${d?'Staged for Google Tasks completion':esc(t.time||'Google Task')}</div></span></label>`}).join(''):'<span class="muted">No active Google Tasks returned.</span>';$('tasks').innerHTML=html;$('overviewTasks').innerHTML=ts.length?ts.slice(0,4).map(t=>`<div class="item"><span>✓</span><span><div class="item-title">${esc(t.title)}</div><div class="item-sub">${esc(t.time||'Google Task')}</div></span></div>`).join(''):'<span class="muted">No active tasks.</span>'}
function taskSourceLines(){const s=doc.byKey.tasks;if(!s)return[];const priority=s.subsections.find(z=>/action priorit/i.test(z.title));const lines=priority?priority.lines:s.lines;return lines.map(x=>x.trim()).filter(x=>/^([-*]|\d+[.)])\s+/.test(x)).map(x=>x.replace(/^[-*]\s+\[[ xX]\]\s*/,'').replace(/^[-*]\s+/,'').replace(/^\d+[.)]\s+/,'').trim())}
function renderHorizonTasks(){const a=taskSourceLines(),s=localStore('horizonTasks'),show=$('showHorizonTasks').checked;$('horizonTasks').innerHTML=a.length?a.map(t=>{const plain=strip(t.replace(/\*\*/g,'')),d=s.has(plain.toLowerCase());return `<label class="item ${d?'done':''}" style="${d&&!show?'display:none':''}"><input class="check" type="checkbox" ${d?'checked':''} onchange='toggleLocal("horizonTasks",${JSON.stringify(plain)},this.checked)'><span class="item-title">${inline(t)}</span></label>`}).join(''):'<span class="muted">No HORIZON-generated actions.</span>'}
function ideaLines(){const s=doc.byKey.ideas;if(!s)return[];return s.lines.map(x=>x.trim()).filter(x=>/^[-*]\s+/.test(x)).map(x=>x.replace(/^[-*]\s+/,'').trim())}
function renderIdeas(){const a=ideaLines(),s=localStore('ideas'),show=$('showIdeas').checked;$('ideas').innerHTML=a.length?a.map(t=>{const plain=strip(t.replace(/\*\*/g,'')),d=s.has(plain.toLowerCase());return `<label class="item ${d?'done':''}" style="${d&&!show?'display:none':''}"><input class="check" type="checkbox" ${d?'checked':''} onchange='toggleLocal("ideas",${JSON.stringify(plain)},this.checked)'><span class="item-title">${inline(t)}</span></label>`}).join(''):'<span class="muted">No current Things to Consider.</span>'}
function eventHtml(a){return a?.length?a.map(e=>`<div class="event"><small>${esc(e.time||'All day')}</small><div class="item-title">${esc(e.title)}</div>${e.note?`<div class="note">${esc(e.note)}</div>`:''}</div>`).join(''):'<span class="muted">No scheduled events.</span>'}
function diag(raw){const expected=['somatic','weather','health','finance','calendar','tasks','gmail','ideas','news'],found=expected.filter(k=>doc.byKey[k]);$('diag').innerHTML=`Frontend build: <b>${BUILD}</b><br>HORIZON characters: ${raw.length}<br>Detected top-level sections: ${doc.sections.length}<br>Mapped expected sections: ${found.length}/9<br>Detected: ${doc.sections.map(s=>esc(s.title)).join(' • ')||'none'}<br>Missing: ${expected.filter(k=>!doc.byKey[k]).join(', ')||'none'}<br>Weather location: ${esc(weatherLoc.label||'unknown')}<br>Intelligence items: ${intel.items?.length||0}`}
function render(){const today=data.calendar?.today||[],tom=data.calendar?.tomorrow||[];$('eventN').textContent=today.length;const c=data.health_nutrition?.total_calories;$('cal').textContent=c===undefined?'—':c+' kcal';$('timeline').innerHTML=eventHtml(today);$('todaySchedule').innerHTML=eventHtml(today);$('tomorrowSchedule').innerHTML=eventHtml(tom);renderTasks();renderHorizonTasks();renderIdeas();$('preamble').innerHTML=renderMd(doc.preamble);renderSection('somatic','somatic');renderSection('weather','weather');renderSection('health','health');renderSection('finance','finance');renderSection('gmail','gmail');renderSection('news','news');renderSection('calendarBrief','calendar');const u=data.briefing?.last_updated||data.system_metadata?.last_updated;$('updated').textContent=u?'Briefing updated '+new Date(u).toLocaleString():'Live briefing loaded'}
async function loadDashboard(){const r=await fetch(WEBHOOK+'?action=getHorizonData&ts='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);data=await r.json();if(data.status==='error')throw Error(data.error);const raw=data.briefing?.plain_text||'';doc=parseHorizon(raw);render();diag(raw);$('syncState').textContent='LAST SYNC • '+new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});$('rawBrief').textContent=raw||'No canonical briefing returned.'}
function clock(){const now=new Date();$('liveClock').textContent=now.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});$('liveDate').textContent=now.toLocaleDateString([],{weekday:'long',month:'short',day:'numeric'})}clock();setInterval(clock,1000);
function loadWeatherLocation(){try{return JSON.parse(localStorage.getItem('aegis_weather_location'))||FALLBACK_LOCATION}catch{return FALLBACK_LOCATION}}
function saveWeatherLocation(x){weatherLoc=x;localStorage.setItem('aegis_weather_location',JSON.stringify(x))}
function locate(){return new Promise(resolve=>{if(!navigator.geolocation)return resolve(FALLBACK_LOCATION);navigator.geolocation.getCurrentPosition(async p=>{let loc={lat:p.coords.latitude,lon:p.coords.longitude,label:`Current location • ${p.coords.latitude.toFixed(3)}, ${p.coords.longitude.toFixed(3)}`,source:'Live location'};try{const r=await fetch(WEBHOOK+`?action=reverseGeocode&lat=${encodeURIComponent(loc.lat)}&lon=${encodeURIComponent(loc.lon)}&ts=${Date.now()}`,{cache:'no-store'});const j=await r.json();if(j.status==='success'&&j.label)loc.label=j.label}catch{}saveWeatherLocation(loc);resolve(loc)},()=>resolve(weatherLoc||FALLBACK_LOCATION),{enableHighAccuracy:false,timeout:7000,maximumAge:900000})})}
function weatherCode(c){return({0:'Clear',1:'Mostly clear',2:'Partly cloudy',3:'Overcast',45:'Fog',48:'Rime fog',51:'Light drizzle',53:'Drizzle',55:'Heavy drizzle',61:'Light rain',63:'Rain',65:'Heavy rain',71:'Light snow',73:'Snow',75:'Heavy snow',80:'Rain showers',81:'Showers',82:'Heavy showers',95:'Thunderstorms',96:'Thunderstorms + hail',99:'Severe thunderstorms'})[c]||'Current conditions'}
async function syncWeather(forceLocation){busy('weatherSync',1,'↻ Syncing…');try{const loc=forceLocation?await locate():(weatherLoc||await locate());weatherLoc=loc;$('weatherLocation').textContent=`${loc.label} • ${loc.source}`;const url=`https://api.open-meteo.com/v1/forecast?latitude=${encodeURIComponent(loc.lat)}&longitude=${encodeURIComponent(loc.lon)}&current=temperature_2m,apparent_temperature,relative_humidity_2m,precipitation,weather_code,wind_speed_10m&hourly=temperature_2m,precipitation_probability,weather_code&daily=temperature_2m_max,temperature_2m_min&temperature_unit=fahrenheit&wind_speed_unit=mph&precipitation_unit=inch&timezone=auto&forecast_days=2`;const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw Error('Weather HTTP '+r.status);const w=await r.json(),cur=w.current||{},d=w.daily||{};$('weatherTemp').textContent=Math.round(cur.temperature_2m)+'°F';$('weatherCondition').textContent=weatherCode(cur.weather_code);$('weatherFeels').textContent=Math.round(cur.apparent_temperature)+'°F';$('weatherHiLo').textContent=`${Math.round(d.temperature_2m_max?.[0])}° / ${Math.round(d.temperature_2m_min?.[0])}°`;$('weatherHumidity').textContent=Math.round(cur.relative_humidity_2m)+'%';const hi=w.hourly?.time||[],pi=w.hourly?.precipitation_probability||[],ti=w.hourly?.temperature_2m||[],ci=w.hourly?.weather_code||[];const now=Date.now(),rows=[];for(let i=0;i<hi.length&&rows.length<6;i++){const ts=new Date(hi[i]).getTime();if(ts>=now-1800000)rows.push({time:hi[i],temp:ti[i],rain:pi[i],code:ci[i]})}$('weatherRain').textContent=(rows[0]?.rain??0)+'%';$('weatherWind').textContent=Math.round(cur.wind_speed_10m)+' mph';$('weatherUpdated').textContent=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});$('weatherHourly').innerHTML=rows.map(x=>`<div class="hour"><small>${new Date(x.time).toLocaleTimeString([],{hour:'numeric'})}</small><b>${Math.round(x.temp)}°</b><small>${x.rain??0}% rain</small></div>`).join('');diag(data.briefing?.plain_text||'')}catch(e){$('weatherCondition').textContent='Weather unavailable';console.warn(e)}finally{busy('weatherSync',0)}}
function intelLabel(k){return({'local-triangle':'Durham / Triangle','nc-policy':'NC / Policy & Health','pc-gaming':'PC Gaming','game-updates':'Game Updates','tarkov':'Escape from Tarkov','industry':'Gaming Industry','deals':'Game Deals','ai-cyber':'AI / Cybersecurity'})[k]||k}
function renderIntel(){const cats=intel.categories||{},entries=Object.entries(cats);$('intelN').textContent=intel.items?.length||0;$('intelSections').innerHTML=entries.length?entries.map(([k,a],idx)=>`<details class="intel-category" ${idx<2?'open':''}><summary><span>${esc(intelLabel(k))}</span><span class="source-badge">${a.length} items</span></summary><div class="intel-list">${a.map(renderIntelItem).join('')}</div></details>`).join(''):'<div class="muted">No intelligence feed loaded. Install/redeploy the v2.3 Apps Script and press Sync Intelligence.</div>';const top=(intel.items||[]).slice(0,6);$('intelPreview').innerHTML=top.length?top.map(renderIntelItem).join(''):'<span class="muted">No live intelligence loaded.</span>'}
function renderIntelItem(x){return `<article class="intel-item"><div class="intel-title"><a href="${esc(x.link||'#')}" target="_blank" rel="noopener noreferrer">${esc(x.title||'Untitled')} ↗</a></div><div class="intel-meta">${esc(x.source||'Source')} • ${x.published?esc(new Date(x.published).toLocaleString()):'Recent'} <span class="source-badge">${esc(x.sourceType||'Editorial')}</span></div>${x.description?`<div class="intel-desc">${esc(strip(x.description).slice(0,260))}</div>`:''}</article>`}
async function syncIntelligence(showToast=true){busy('intelSync',1,'↻ Syncing…');try{const r=await fetch(WEBHOOK+'?action=getIntelligence&ts='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);const j=await r.json();if(j.status==='error'||!j.categories)throw Error(j.error||'v2.3 intelligence endpoint unavailable');intel=j;renderIntel();if(showToast)toast('Live intelligence synced');diag(data.briefing?.plain_text||'')}catch(e){if(showToast)toast('Intelligence backend update required');console.warn('Intel sync:',e)}finally{busy('intelSync',0)}}
(async function init(){try{await loadDashboard();stat('SYSTEM READY')}catch(e){$('out').textContent='INITIAL SYNC ERROR: '+e.message;stat('SYNC FAILED','var(--bad)')}syncWeather(false);syncIntelligence(false);setInterval(()=>syncWeather(false),20*60*1000);if('serviceWorker'in navigator)addEventListener('load',async()=>{try{const r=await navigator.serviceWorker.register('./sw.js?v='+BUILD);await r.update()}catch{}})})();
