const Q=[
['The way to get started is to quit talking and begin doing.','Walt Disney'],
['Do what you can, with what you have, where you are.','Theodore Roosevelt'],
['The future belongs to those who believe in the beauty of their dreams.','Eleanor Roosevelt'],
["It always seems impossible until it's done.",'Nelson Mandela'],
["You don't have to be great to start, but you have to start to be great.",'Zig Ziglar'],
['Action is the foundational key to all success.','Pablo Picasso'],
['A journey of a thousand miles begins with a single step.','Lao Tzu'],
["Opportunities don't happen, you create them.",'Chris Grosser'],
["Don't watch the clock; do what it does. Keep going.",'Sam Levenson'],
['Small daily improvements over time lead to stunning results.','Robin Sharma'],
['Dream big and dare to fail.','Norman Vaughan'],
['The secret of getting ahead is getting started.','Mark Twain'],
['Start where you are. Use what you have. Do what you can.','Arthur Ashe'],
["Your time is limited, so don't waste it living someone else's life.",'Steve Jobs'],
['Aim for the moon. If you miss, you may hit a star.','W. Clement Stone'],
["You miss 100% of the shots you don't take.",'Wayne Gretzky'],
['The only limit to our realization of tomorrow will be our doubts of today.','Franklin D. Roosevelt'],
['Whatever you are, be a good one.','Abraham Lincoln'],
['The critical ingredient is getting off your butt and doing something.','Nolan Bushnell'],
['In any given moment we have two options: to step forward into growth or step back into safety.','Abraham Maslow'],
['Fall seven times and stand up eight.','Japanese Proverb'],
['It does not matter how slowly you go as long as you do not stop.','Confucius'],
['Rock bottom became the solid foundation on which I rebuilt my life.','J.K. Rowling'],
['Tough times never last, but tough people do.','Robert H. Schuller'],
["If you're going through hell, keep going.",'Winston Churchill'],
['Success is not final, failure is not fatal: it is the courage to continue that counts.','Winston Churchill'],
['Hardships often prepare ordinary people for an extraordinary destiny.','C.S. Lewis'],
['Turn your wounds into wisdom.','Oprah Winfrey'],
['You may encounter many defeats, but you must not be defeated.','Maya Angelou'],
['A river cuts through rock, not because of its power, but because of its persistence.','Jim Watkins'],
['The greatest glory in living lies not in never falling, but in rising every time we fall.','Nelson Mandela'],
['Out of difficulties grow miracles.','Jean de La Bruyère'],
['Defeat is not the worst of failures. Not to have tried is the true failure.','George Edward Woodberry'],
['We must embrace pain and burn it as fuel for our journey.','Kenji Miyazawa'],
['When everything seems to be going against you, remember that the airplane takes off against the wind, not with it.','Henry Ford'],
["Courage doesn't always roar. Sometimes courage is the quiet voice at the end of the day saying, 'I will try again tomorrow.'",'Mary Anne Radmacher'],
['Failure is simply the opportunity to begin again, this time more intelligently.','Henry Ford'],
['Strength does not come from winning. Your struggles develop your strengths.','Arnold Schwarzenegger'],
['The oak fought the wind and was broken, the willow bent when it must and survived.','Robert Jordan'],
["Everything you've ever wanted is on the other side of fear.",'George Addair'],
["Whether you think you can or you think you can't, you're right.",'Henry Ford'],
['Life is 10% what happens to you and 90% how you react to it.','Charles R. Swindoll'],
['Change your thoughts and you change your world.','Norman Vincent Peale'],
['We suffer more often in imagination than in reality.','Seneca'],
['Happiness is not something ready made. It comes from your own actions.','Dalai Lama'],
['The mind is everything. What you think you become.','Buddha'],
['Keep your face always toward the sunshine—and shadows will fall behind you.','Walt Whitman'],
['You have power over your mind—not outside events. Realize this, and you will find strength.','Marcus Aurelius'],
['Dwell on the beauty of life. Watch the stars, and see yourself running with them.','Marcus Aurelius'],
['Gratitude turns what we have into enough.','Aesop'],
['Pessimism leads to weakness, optimism to power.','William James'],
['If you change the way you look at things, the things you look at change.','Wayne Dyer'],
["Nothing is impossible, the word itself says 'I'm possible'!",'Audrey Hepburn'],
['To live is the rarest thing in the world. Most people exist, that is all.','Oscar Wilde'],
['The energy of the mind is the essence of life.','Aristotle'],
["Don't let yesterday take up too much of today.",'Will Rogers'],
['Peace comes from within. Do not seek it without.','Buddha'],
['The man who moves a mountain begins by carrying away small stones.','Confucius'],
['Look for the good in every situation, seek the valuable lesson in every defeat.','Brian Tracy'],
['There are far, far better things ahead than any we leave behind.','C.S. Lewis'],
['To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.','Ralph Waldo Emerson'],
["Be who you are and say what you feel, because those who mind don't matter, and those who matter don't mind.",'Bernard M. Baruch'],
['I am not what happened to me, I am what I choose to become.','Carl Jung'],
['No one can make you feel inferior without your consent.','Eleanor Roosevelt'],
['The privilege of a lifetime is to become who you truly are.','Carl Jung'],
['Live as if you were to die tomorrow. Learn as if you were to live forever.','Mahatma Gandhi'],
['The two most important days in your life are the day you are born and the day you find out why.','Mark Twain'],
['Dare to be remarkably you.','Unknown'],
['What lies behind us and what lies before us are tiny matters compared to what lies within us.','Ralph Waldo Emerson'],
['Have courage to use your own reason.','Immanuel Kant'],
['You only live once, but if you do it right, once is enough.','Mae West'],
["Do what you feel in your heart to be right—for you'll be criticized anyway.",'Eleanor Roosevelt'],
['Freedom lies in being bold.','Robert Frost'],
['It is not the critic who counts; not the man who points out how the strong man stumbles... The credit belongs to the man who is actually in the arena